### ISSUE TITLE
Jenkins theme?

### ISSUE THREAD

**Issue by ecumene-software** [team-jgloom/team-jgloom.github.io#1]
Jenkins is a python (I think) based blogging platform and is kinda hackable. We can use it for the site, and there's plenty of themes+support around it.

Here are some interesting themes:
http://jekyllthemes.org/themes/devjournal/
http://jekyllthemes.org/themes/safarnama/
http://jekyllthemes.org/themes/moon/
http://jekyllthemes.org/themes/carte/
http://jekyllthemes.org/themes/centrarium/

**Comment by zgoethel12** [comment]
Or custom code - I'm good with HTML/CSS

**Comment by zgoethel12** [comment]
I just bought my domain http://jibini.net/ and hosted it at https://github.com/jibini-media/jibini-media.github.io

It consists of a simple Java page assembly tool and page contents, just read the README if you want to.  The code at my website is what I wrote from scratch, and I've been working on a mobile version.

**Comment by ecumene-software** [comment]
Hehe, aren't we all

I have a good idea for a static page, and a friend of mine is a sort of professional in that field. I'll hack something together soon.
